import Head from "next/head";
import styles from "../styles/Home.module.css";
import Main from "../components/Main";
import styled from "styled-components";

const AppStyle = styled.div`
  height: 100vh;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  background: #OCOB10;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AppStyle>
        <h3>Password Generator</h3>
        <Main />
      </AppStyle>
    </div>
  );
}
